services:
  restreamer:
    image: ghcr.io/kbats183/simple-rtmp-restreamer:latest
    container_name: "restreamer"
    environment:
      - BASIC_AUTH_USER=live
      - BASIC_AUTH_PASS=changeme
    volumes:
      - ./simple-rtmp-restreamer.data.json:/app/simple-rtmp-restreamer.data.json
      - ./web:/app/web
    ports:
      - "1935:1935"
      - "6070:6070"
    restart: unless-stopped
